title: Jake Sandor # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Fellow- Maria McLaughlin for Pennsylvania Supreme Court 
  <br><br>
  Recent graduate of University of Georgia's Masters of Science in Business Analytics program, currently looking for work as a data analyst or researcher. I am extremely passionate about environmentalism, public policy, labor rights, and economics. 
  <br><br>
  <a href="https://www.linkedin.com/in/jake-sandor/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
